### ISSUE TITLE
%debug_package macro does not handle obsoletes

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/rpm-os2#3]
Installing libc-debug and libc-debuginfo or installing libc-debuginfo when libc-debug has been installed will fail with:

Transaction Check Error:
  file /@unixroot/usr/bin/emxaout.dbg from install of libc-debug-0.6.6-40.oc00.i686 conflicts with file from package libc-debuginfo-1:0.1.9-1.oc00.pentium4 

[and several other conflicting files]

In fact, libc-debuginfo should obsolete libc-debug, but the macro does not provide a method for doing this at package build time.

**Comment by SilvanScherrer** [comment]
this is a well known fact. In theory no one should ever install any debug stuff beside the developer asks for. and afterwards it should always be deleted. as it's not only that the obsoletes tag is missing. there are more tags missing. in a perfect world we would fix them all. but in this world we just try our best.

**Comment by SilvanScherrer** [comment]
and for the completeness, this change was introduced when we updated to rpm version 4.11. And even in the upstream version is no obsolete tag included.
